# Generated by Django 4.0 on 2022-02-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalstest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='model_name',
            new_name='name',
        ),
    ]
