# Generated by Django 4.0 on 2022-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalstest', '0002_rename_model_name_signal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
