# Generated by Django 4.0 on 2022-02-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalstest', '0003_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='font_size',
            field=models.IntegerField(default=12),
        ),
    ]
